name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: Tell us what should happen
      placeholder: Short and explicit description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: "Current Behavior"
      description: Tell us what happens instead of the expected behavior.
      placeholder: Short and explicit description of what is happening instead.
    validations:
      required: true

